DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS Order_Product;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Profile;

CREATE TABLE Product (
    product_uuid BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    price DOUBLE,
    created_date DATE,
    modified_date TIMESTAMP
);

